Update denis_repo.yml

diff --git a/.github/workflows/denis_repo.yml b/.github/workflows/denis_repo.yml
--- a/.github/workflows/denis_repo.yml
+++ b/.github/workflows/denis_repo.yml
@@ -1,5 +1,3 @@
-#This repo is for learning purpose
-
 name: CI/CD Pipeline
 
 on:
@@ -11,7 +9,7 @@ on:
     branches:
       - main
       - develop
-
+      
 env:
   BRANCH: ${{ github.head_ref || github.ref_name }}
 concurrency:
@@ -35,7 +33,7 @@ ci:
   name: CI
   runs-on: ubuntu-latest
   needs: set variables
-  if: ${{ (needs.set_variables.outputs.has_python_changes 'true') || (needs...
+  if: ${{ (needs.set_variables.outputs.has_python_changes 'true') || (needs.sets_variables.outputs.has_tablea_changes == 'true')}}
   steps:
     - name: Check out changes
       uses: actions/checkout@v4
@@ -44,10 +42,11 @@ ci:
       with:
         python-version: 3.9
     - name: Install dependencies
-    run: |
-      python-m pip install --upgrade pip
-      pip install -r requirements.txt
-      python setup.py install
+      run: |
+        python-m pip install --upgrade pip
+        pip install -r requirements.txt
+        python setup.py install
+        pip install pytest pytest-cov
     - name: Run PyLint
       run: |
         pylint --recursive=y etl/tests/tableau/
@@ -55,4 +54,24 @@ ci:
       if : ${{ needs.set_variables.outputs.has.tableau_changes == 'true'}}
       run: |
         pytest tests/tableau
-      
+    - name: Run backend unit tests
+      if: ${{ needs.set_varibales.ouputs.has_python_changes == 'true'}}
+      run : |
+        pytest tests/unit tests/integration tests/mocks --cov=etl --cov-report=term-missing --cov-report=html --cov-config=.coveragerc
+    - name: Upload test results
+      uses: action/upload-artifacts@v4
+      with: 
+        name: pytest-results
+        path: htmlcpv/
+        # Use always() to always run this step tp publish test results when there are test failures
+        if: ${{always() }}
+end2end:
+  name: END to END tests
+  runs-on: ubuntu-latest
+  needs: set_variables
+  if: ${{ needs.set_variables.outputs.has_etl_changes == 'true'}}
+  steps:
+    - name: Check out changes
+      uses: actions/changes@v4
+    - name: Set up Python
+          
